### ISSUE TITLE
Xt7BindKeys

### ISSUE THREAD

**Issue by Silver-Shroud** [kokoko3k/xt7-player-mpv#11]
http://xt7-player.sourceforge.net/xt7forum/viewtopic.php?f=3&t=231
[set-output.txt](https://github.com/kokoko3k/xt7-player-mpv/files/139549/set-output.txt)

**Comment by kokoko3k** [comment]
Output seems fine.
Tomorrow I'll make a detailed debug build  for you to try.
When you'll be hit by the bug, i'll need his console output, so i can understand why it fails.

**Comment by kokoko3k** [comment]
Wait a sec, do you have xbindkeys installed and accessible by your $PATH?
And if not, could you please verify if it still happens after installing it?

**Comment by Silver-Shroud** [comment]
I didn't have it installed. Installing it fixed the issue.
I don't have any global hotkeys set, so I fail to see how this is a dependency issue?

**Comment by kokoko3k** [comment]
It is an optional dep, but i'll fix that asap, 
meanwhile, thanks for the report!

**Comment by Silver-Shroud** [comment]
Thanks for helping me out!

**Comment by kokoko3k** [comment]
This should be fixed by this:
https://github.com/kokoko3k/xt7-player-mpv/commit/924293a458d49998245885b9e1a8e1bd5056faf3
Could you please check if all works as it should even if no xbindkeys is installed in the latest git code, so i can close this?

**Comment by Silver-Shroud** [comment]
Huzzah! Issue fixed!
