### ISSUE TITLE
Start were you left off feature is limited.

### ISSUE THREAD

**Issue by Silver-Shroud** [kokoko3k/xt7-player-mpv#13]
http://xt7-player.sourceforge.net/xt7forum/viewtopic.php?f=4&t=230

Could this feature please be expanded to resume any file from where it was left off at any point instead of just saving the last song/video and position on exit?

**Comment by kokoko3k** [comment]
https://github.com/kokoko3k/xt7-player-mpv/commit/1f1673fc6add4e0ab81e9d08b89995ce4e5f356c
There is another option that extends the previous one to the 15 recently played items.
It is enabled by default.
As there are many changes involved, **i ask you to deeply test the new code for regressions, thanks.**

**Comment by Kakashi-sensei** [comment]
Has the AUR package been updated?
warning: xt7-player-mpv-git-20150430-1 is up to date -- reinstalling

**Comment by Silver-Shroud** [comment]
What can I do to test? These new changes seem to be working.

**Comment by kokoko3k** [comment]
Well, nothing particular, if all seems to work, i'll close this by now then.
