### ISSUE TITLE
PPA

### ISSUE THREAD

**Issue by wingedonezero** [kokoko3k/xt7-player-mpv#14]
Can you make a ppa i know ive seen one but it hasnt been updated in several years. Id love to try your player out but im not very good with the compiling part. And im sure many other users would benefit as well.

**Comment by kokoko3k** [comment]
I'm sorry, but i don't use ubuntu or similar,(i'm actually mantaining tha Arch Linux package)
Once you installed the whole gambas3 (http://gambaswiki.org/wiki/install/ubuntu), just follow the instructions posted on the main xt7-player-mpv page here on github (https://github.com/kokoko3k/xt7-player-mpv/blob/master/README.md)
Don't forget to install youtube-dl and mpv, of course.
