### ISSUE TITLE
german translation file update

### ISSUE THREAD

**Issue by martinkg** [kokoko3k/xt7-player-mpv#19]
attached is a new lang file (rename it to de.po) for the german translation, please push it to git.

[xt7-player-mpv-de.po.txt](https://github.com/kokoko3k/xt7-player-mpv/files/573433/xt7-player-mpv-de.po.txt)

Thanks martinkg

**Comment by martinkg** [comment]
please use this file with last fixes:
https://martinkg.fedorapeople.org/xt7-player-mpv-de.po
Thanks martinkg

**Comment by kokoko3k** [comment]
Many thanks, just grabbed.

**Comment by martinkg** [comment]
please update the german lang file again.
https://martinkg.fedorapeople.org/xt7-player-mpv-de.po
Thanks martinkg

**Comment by kokoko3k** [comment]
Done, thanks

**Comment by martinkg** [comment]
german translation is now finalyzed, please update file again.
https://martinkg.fedorapeople.org/xt7-player-mpv-de.po
Thanks martinkg

**Comment by kokoko3k** [comment]
I don't get it, the last one seems almost identical:

```
[11:12:55]  cd ~/tmp
root@Gozer# ls -la *.po
-rw-r--r-- 1 root root 172076 nov  9 11:11 NEWNEW_xt7-player-mpv-de.po
-rw-r--r-- 1 root root 172076 nov  8 15:29 OK_xt7-player-mpv-de.po
-rw-r--r-- 1 root root 179200 nov  7 11:20 xt7-player-mpv-de.po

[11:12:59]  cd ~/tmp
root@Gozer# diff OK_xt7-player-mpv-de.po NEWNEW_xt7-player-mpv-de.po
5c5
< "PO-Revision-Date: 2016-11-08 14:10 UTC\n"
---
> "PO-Revision-Date: 2016-11-08 14:11 UTC\n"
```

**Comment by martinkg** [comment]
please try it again.

**Comment by kokoko3k** [comment]
Yes, Just did it, thanks again!

**Comment by martinkg** [comment]
added missing translations again, please take it.
many thanks.

Maybe it's possible to have the translation on https://www.transifex.com ?

**Comment by kokoko3k** [comment]
Hi, and sorry for the delay, 
I don't know about transifex, but it seems it is free only for the 15 day trial.
Going to merge your new translation, thanks.
