### ISSUE TITLE
Can't reproduce any file

### ISSUE THREAD

**Issue by cesasol** [kokoko3k/xt7-player-mpv#2]
When I try to reproduce any file or stream the comandline give me this error 

MplayerClass.do_play.557:  LC_ALL=C mpv --config=no --input-conf=/tmp/FakeInput.conf --load-scripts=no --osc=no --dvbin-file=/home/cesasol/.config/mpv/channels.conf.ter --wid=54526096 --cursor-autohide=no --cursor-autohide-fs-only=no --audio-pitch-correction=no --ytdl=no --input-cursor=no --input-vo-keyboard=no --cache=1024 --cache-initial=0 --cache-seek-min=500 --audio-channels=2 --softvol-max=100 --hwdec=auto --dvbin-card=1 --dvbin-timeout=10 --demuxer-lavf-probesize=512000 --sub-text-font="Bitstream Vera Sans:style=bold" --sub-text-font-size=24 --sub-text-border-size=1 --sub-text-border-color=#FF000000 --sub-text-shadow-offset=1 --sub-text-shadow-color=#BF000000 --osd-font="Bitstream Vera Sans:style=bold" --osd-font-size=22 --osd-border-size=1 --osd-border-color=#FF000000 --osd-shadow-offset=1 --osd-shadow-color=#BF000000 --sub-auto=exact --alang=en,eng --slang=en,eng --volume=48 --input-file=/home/cesasol/.config/gambas3/xt7-Player-mpv/.InputPipes/Xt7Input-44991 --msg-color=no --msg-level=all=v,cplayer=status --term-status-msg="" /home/cesasol/Música/1997\ Pat\ Metheny\ -\ Imaginary\ Day\ (1997)/03.\ Into\ The\ Dream.mp3        LC_ALL=C mpv --config=no --input-conf=/tmp/FakeInput.conf --load-scripts=no --osc=no --dvbin-file=/home/cesasol/.config/mpv/channels.conf.ter --wid=54526096 --cursor-autohide=no --cursor-autohide-fs-only=no --audio-pitch-correction=no --ytdl=no --input-cursor=no --input-vo-keyboard=no --cache=1024 --cache-initial=0 --cache-seek-min=500 --audio-channels=2 --softvol-max=100 --hwdec=auto --dvbin-card=1 --dvbin-timeout=10 --demuxer-lavf-probesize=512000 --sub-text-font="Bitstream Vera Sans:style=bold" --sub-text-font-size=24 --sub-text-border-size=1 --sub-text-border-color=#FF000000 --sub-text-shadow-offset=1 --sub-text-shadow-color=#BF000000 --osd-font="Bitstream Vera Sans:style=bold" --osd-font-size=22 --osd-border-size=1 --osd-border-color=#FF000000 --osd-shadow-offset=1 --osd-shadow-color=#BF000000 --sub-auto=exact --alang=en,eng --slang=en,eng --volume=48 --input-file=/home/cesasol/.config/gambas3/xt7-Player-mpv/.InputPipes/Xt7Input-44991 --msg-color=no --msg-level=all=v,cplayer=status --term-status-msg="" /home/cesasol/Música/1997\ Pat\ Metheny\ -\ Imaginary\ Day\ (1997)/03.\ Into\ The\ Dream.mp3
MplayerClass.do_play.582: /tmp/gambas.1001/15791/39.tmp 15791 18092
when $1 dies, $2 will be killed
MplayerClass.get_mediainfo.684: EE      Playback didn't started or timeout waiting for it to start
FMain.Play.2551: mplayer.get_mediainfo()        0,22214698791504
MplayerClass.set_option.402:  ytdl      yes
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
cat: /proc/16157/cmdline: No existe el fichero o el directorio
cat: /proc/18092/cmdline: No existe el fichero o el directorio
mpv pid 18092 is dead, exiting now

And This keeps prompting 
cat: /proc/18092/cmdline: No existe el fichero o el directorio

**Comment by kokoko3k** [comment]
Seems mpv is crashing or refuses to start for some reason.
Are you using mpv 0.8.2?
Could you please post the content of the log window? 
Menu button -> ? -> show logs
please, post both "output" and "modules" tabs content.

**Comment by kokoko3k** [comment]
Non answer, i'm assuming you solved the issue.
If not, feel free to answer.
