### ISSUE TITLE
Double-click to fullscreen pauses for a second.

### ISSUE THREAD

**Issue by Silver-Shroud** [kokoko3k/xt7-player-mpv#20]
As the title describes.
Coming out of fullscreen doesn't do so.
Using git.

**Comment by kokoko3k** [comment]
It helped me with an nvidia ION1 setup in the past.
Uncheck general options -> Tweaks -> Pause video when going fullscreen.
I may remove it from being set as default in the future.

**Comment by Silver-Shroud** [comment]
Thanks!
