### ISSUE TITLE
Application crashes if all tabs (youtube, dvb-t, etc.) are hidden in context menu

### ISSUE THREAD

**Issue by ghost** [kokoko3k/xt7-player-mpv#21]
...well, that's it.
Anybody can confirm that?

**Comment by kokoko3k** [comment]
Yes, confirmed.
It needs to be fixed, but how?
Why, in the first place, are you trying to hide alll of the tabs?

**Comment by kokoko3k** [comment]
Fixed by https://github.com/kokoko3k/xt7-player-mpv/commit/a2b64f97fa33b02de87fbf2ba51c5f8c9d9a5662
