### ISSUE TITLE
xt7 crashes when selecting Playlist - Set a cover

### ISSUE THREAD

**Issue by martinkg** [kokoko3k/xt7-player-mpv#22]
reprocuce:
with recent version xt7-player-mpv-0.28.3100
Start xt7-player
Select playlist - Set a cover

error message on console:
gb.form: DirCache.CheckValid.57: File or directory does not exist
GridView._CheckCell.1346: Bad row index
GridView._CheckCell.1346 _GridView_Cell.GetData.31 _GridView_Cell.Text_Read.40 FMain.MenuPlsSetCover_click.9248 MenuButton.HandleMenu.187 MenuButton.Arrow_Click.216 MenuButton.DrawingArea_MouseDown.346

error message window: 
![xt7-player-mpv_001](https://user-images.githubusercontent.com/2564124/40425642-4277adca-5e99-11e8-8686-ca51625c5c39.png)

**Comment by kokoko3k** [comment]
Should be fixed by: 
https://github.com/kokoko3k/xt7-player-mpv/commit/767eb7631062a9cc8bfc5b15f425a8a6241fd020
