### ISSUE TITLE
Invalid parameter for --sub-auto (value gets localized?)

### ISSUE THREAD

**Issue by Maltragor** [kokoko3k/xt7-player-mpv#24]
Version: 0.29.3122
Language / localization: German

It seems that some values for "--sub-auto" you can select in the 'subtitle and OSD' config dialog gets translatet to german (english exact is german exakt):

> --sub-auto=exakt

So the parameter is unknown and the following error is shown:

> Invalid value for option sub-auto: exakt
> Valid values are:
>    no
>    exact
>    fuzzy
 >   all

**Comment by kokoko3k** [comment]
Thank you so much, i spotted other mistakes too.
If you find more, please report ;)
