### ISSUE TITLE
mpv: Error parsing option cache-initial (option not found)

### ISSUE THREAD

**Issue by xOneca** [kokoko3k/xt7-player-mpv#26]
Commandline:
    LC_ALL=C mpv --config=no --load-scripts=no --osc=no --dvbin-file=/home/xoneca/.config/mpv/channels.conf.ter --wid=65011853 --cursor-autohide=no --cursor-autohide-fs-only=no --audio-pitch-correction=no --audio-display=no --ytdl=no --input-cursor=no --input-vo-keyboard=no --cache=auto --cache-initial=0 --cache-seek-min=500 --af-add=scaletempo --audio-device=auto --volume-max=100 --ad-lavc-ac3drc=1.0 --audio-channels=2 --hwdec=no --dvbin-card=1 --dvbin-timeout=10 --demuxer-lavf-probesize=512000 --audio-device=auto --sub-bold=yes --sub-font="Bitstream Vera Sans" --sub-font-size=24 --sub-border-size=1 --sub-border-color=#FF000000 --sub-shadow-offset=1 --sub-shadow-color=#BF000000 --osd-bold=yes --osd-font="Bitstream Vera Sans" --osd-font-size=22 --osd-border-size=1 --osd-border-color=#FF000000 --osd-shadow-offset=1 --osd-shadow-color=#BF000000 --sub-auto=exact --sub-codepage=iso-8859-1 --alang=en,eng --slang=en,eng --volume=100 --input-file=/home/xoneca/.config/gambas3/xt7-Player-mpv/.InputPipes/Xt7Input-2604 --msg-color=no --msg-level=all=v,cplayer=status,dvdnav=no,disc=no --input-default-bindings=no --term-status-msg=MPV_PLAY_IS_FULLY_INITIALIZED --force-seekable=yes --script=/tmp/gambas.1000/7071/killer.lua --ytdl=yes 'http://192.168.0.10:55555/neox'

    Options:
    --config=no
    --load-scripts=no
    --osc=no
    --dvbin-file=/home/xoneca/.config/mpv/channels.conf.ter
    --wid=65011853
    --cursor-autohide=no
    --cursor-autohide-fs-only=no
    --audio-pitch-correction=no
    --audio-display=no
    --ytdl=no
    --input-cursor=no
    --input-vo-keyboard=no
    --cache=auto
    --cache-initial=0
    --cache-seek-min=500
    --af-add=scaletempo
    --audio-device=auto
    --volume-max=100
    --ad-lavc-ac3drc=1.0
    --audio-channels=2
    --hwdec=no
    --dvbin-card=1
    --dvbin-timeout=10
    --demuxer-lavf-probesize=512000
    -- audio-device=auto
    --sub-bold=yes
    --sub-font="Bitstream Vera Sans"
    --sub-font-size=24
    --sub-border-size=1
    --sub-border-color=#FF000000
    --sub-shadow-offset=1
    --sub-shadow-color=#BF000000
    --osd-bold=yes
    --osd-font="Bitstream Vera Sans"
    --osd-font-size=22
    --osd-border-size=1
    --osd-border-color=#FF000000
    --osd-shadow-offset=1
    --osd-shadow-color=#BF000000
    --sub-auto=exact
    --sub-codepage=iso-8859-1
    --alang=en,eng
    --slang=en,eng
    --volume=100
    --input-file=/home/xoneca/.config/gambas3/xt7-Player-mpv/.InputPipes/Xt7Input-2604
    --msg-color=no
    --msg-level=all=v,cplayer=status,dvdnav=no,disc=no
    --input-default-bindings=no
    --term-status-msg=MPV_PLAY_IS_FULLY_INITIALIZED
    --force-seekable=yes
    --script=/tmp/gambas.1000/7071/killer.lua
    -- ytdl=yes
    --  ytdl=yes

    Error parsing option cache-initial (option not found)
    Setting commandline option --cache-initial=0 failed.
    Exiting... (Fatal error)

Does not allow playing any file, local or remote.

Version information:

    xt7-player-mpv: 0.24.392

    System.fullversion: 3.13.0

    System.Architecture: x86_64

    mpv:
    mpv 0.30.0+git.1567376743.6d90517275 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
    built on Sep  2 2019
    ffmpeg library versions:
    libavutil       56.31.100
    libavcodec      58.54.100
    libavformat     58.29.100
    libswscale      5.5.100
    libavfilter     7.57.100
    libswresample   3.5.100
    ffmpeg version: 4.2

**Comment by kokoko3k** [comment]
Hi,
from the log it seems you're mixing an unreleased mpv version (from git repo) with an ancient xt7-player.
Chances that it would work are near to zero.
Please, upgrade xt7 to the latest stable release (0.29.3122 or even git) and/or mpv to the latest stable (0.29.1).
If you've still problems, feel free to reopen this one.

**Comment by xOneca** [comment]
Yeah, sorry. It was fixed in that release (91616e4a). It seems Packman repo (from where I get xt7-player) is a bit outdated... :/

**Comment by xOneca** [comment]
Well, with latest xt7-player now it gives error on another cache option:

    Invalid value for option cache: 25600
    Valid values are:
        no
        auto
        yes
    Error parsing option cache (option parameter could not be parsed)
    Setting commandline option --cache=25600 failed.
    Exiting... (Fatal error)

I'm not sure when changed mpv option...

**Comment by kokoko3k** [comment]
...Me neither.
I don't/can't follow every single mpv commit.
Latest mpv stable release is v**0.29**.1, this is the one latest xt7 (**0.29**.3142) is coded against.

Use **stable xt7+stable mpv** and you'll get a working player :)

Sure, when the new mpv will be out, i'll provide a working implementation of xt7.
Leave this closed or reopen it till that time will come ;)

**Comment by kokoko3k** [comment]
I identified the problem and i'll write a (following) side note as a reminder for me; it seems i can just "fix" it in advance without breaking anything.

> New:
> --cache=<yes|no|auto>
>     Decide whether to use network cache settings (default: auto).
>     If enabled, use the maximum of --cache-secs and --demuxer-max-bytes for the cache size. If disabled, --cache-pause and related are implicitly disabled.
>     The auto choice sets this depending on whether the stream is thought to involve network accesses (this is an imperfect heuristic).
> 
> In xt7, use --cache=yes + --demuxer-max-bytes=# + --demuxer-max-back-bytes=#
> instead of --cache=KBytes
> 
> property: demuxer-cache-duration remains so there will be no problem with visual cache feedback
> 


..i'll reopen this; will close as soon as the fix will land.

Well... thanks for reporting in advance :-P

**Comment by xOneca** [comment]
I confirm the fix. Thank you very much!
