### ISSUE TITLE
homepage in app send to http://xt7player.homelinux.org/xt7forum which is not online 

### ISSUE THREAD

**Issue by sergiomb2** [kokoko3k/xt7-player-mpv#27]
homepage in app send to http://xt7player.homelinux.org/xt7forum which is not online .
in [1] Desktop.Open("http://xt7player.homelinux.org/xt7forum")

[1]
https://github.com/kokoko3k/xt7-player-mpv/blob/0e26421e0333c2d6203b6b2ca456a601d57814c6/.src/Form/FMain.class#L7650

**Comment by kokoko3k** [comment]
Thanks,
Fixed in https://github.com/kokoko3k/xt7-player-mpv/commit/17fba2bc5a76ebeee0dbc3f1905b4fb1d29fa645
