### ISSUE TITLE
Program Crash on Manjaro (Missing Icon)

### ISSUE THREAD

**Issue by mu150** [kokoko3k/xt7-player-mpv#28]
The program crashes when running `./xt7-player-mpv.gambas`  with error:
```
This application has raised an unexpected error and must abort.

[13] Null object.

covermanager.DefaultLibraryIcon.1314
```
Pressing ignore causes the error to pop up again.
Here is the output in terminal:
```
covermanager.DefaultLibraryIcon.1314: #13: Null object
covermanager.DefaultLibraryIcon.1314 FMain.FileView1_Icon.9526 FileView.GetIcon.196 FileView.RefreshView.426 FileView.Refresh_Timer.601 GeneralOptions.FirstLoadIfNeeded.28 global.SaveAllSettings.476 FMain.ReallySaveAllSettings.5141 FMain.MainInit.1154 zzzFake.Start.58 StartClass.main.41 
```
So it seems the problem is a missing icon?

I am using the latest version of Gambas and I only get one compilation warning which seems unrelated:
`gbc3: warning: unable to compile translation file with 'msgfmt': de.po`

**Comment by kokoko3k** [comment]
Hi and thank you for submitting the bug report.
It happens only when one starts the program for the very first time, so I never faced it.
It should be fixed in the latest git.
