### ISSUE TITLE
crashes when doing an empty library search

### ISSUE THREAD

**Issue by tgys** [kokoko3k/xt7-player-mpv#3]
i typed something in the library search box, typed 'enter' and it crashed giving me these errors:
This application has raised an unexpected
error and must abort.
Bad row index.
GridView._CheckCell.1303
I'm using the package in the arch linux AUR.
xt7-player-mpv: 0.9.2371

System.fullversion: 3.7.1

System.Architecture: x86_64

mpv: 

System.backtrace:
FMain.SearchField_Activate.5609

**Comment by kokoko3k** [comment]
Thanks for reporting, 
I'm on vacations; will check this in 2..3 weeks.

**Comment by kokoko3k** [comment]
It should be fixed here:
https://github.com/kokoko3k/xt7-player-mpv/commit/2d62076c431305d9772aacc976ee05b569611f07
