### ISSUE TITLE
Where should the gambas/binaries directory be located?

### ISSUE THREAD

**Issue by cipricus** [kokoko3k/xt7-player-mpv#30]
It is said:

```
After you installed gambas 3, just checkout and compile xt7 that way:

# git clone https://github.com/kokoko3k/xt7-player-mpv.git
# cd xt7-player-mpv/
# /path/to/gambas/binaries/gbc3 -e -a -g -t -p -m
# /path/to/gambas/binaries/gba3
# ./xt7-player-mpv.gambas
```
But I [cannot find that path on Kubuntu](https://askubuntu.com/q/1329541/925128).

**Comment by kokoko3k** [comment]
I'm sorry, but i don't use kubuntu, so I ignore how gambas is packaged there.
find / -name "gbc3"
find / -name "gba3"
if no results, then probably you need to install other packages.
