### ISSUE TITLE
no audio from xt7-player-mpv when playing files(user-error, low volume set)

### ISSUE THREAD

**Issue by silverhikari** [kokoko3k/xt7-player-mpv#33]
when trying to play a file(the file is .m4a) along with other files formats such as flac and mkv with xt7-player, and i get no sound from any of the files tested. i have played the files in mpv to see if mpv can play the files and that the files are not corrupted, and it does play them.

i have check audio applications when running and the program does appear there but with no sound activity,

i have gone in to the general options and selected as the audio device as the current device i am using instead of leaving on auto and still no sound.

i have look through the logs when running the program with -v though i have not seem anything that would standout though i could be missing something. the log is located here(https://paste.ee/p/5KkVQ)

xt7-player-mpv version: 0.34.3172

mpv version:mpv 0.34.1-dirty
 libavutil       57.17.100
 libavcodec      59.18.100
 libavformat     59.16.100
 libswscale      6.4.100
 libavfilter     8.24.100
 libswresample   4.3.100

ffmpeg: n5.0.1

gambas3-runtime version: 3.17.2

pipewire version:0.3.52

OS: Manjaro/Linux

Enviroment: KDE

**Comment by kokoko3k** [comment]
Please, past the output from the log window too (both tabs) while "playing" the audio.

**Comment by silverhikari** [comment]
nevermind it seems it was user error as i noticed it seems the volume had defaulted to 12% in the program and audio of the program does not seemed linked to the audio volume in the applications volume in KDE
