### ISSUE TITLE
App throws Overflow error at startup 

### ISSUE THREAD

**Issue by Freemason-12** [kokoko3k/xt7-player-mpv#34]
When I launch it from the terminal I get this error:
```
WARNING:----------------------------------------------
        Your ffmpeg has not been compiled with ladspa support
        You will not be able to use any ladspa filter
        and ladspahelper window will be unavaileble in xt7.
        Recompile ffmpeg with ladspa support or ask your
        distribution mantainers to do that.

audioform.AudioForm.0: #7: Overflow
audioform.AudioForm.0 audioform.@new.0 FMain.SetStyle_early.948 FMain.ReLoadCurrentProfile.8457 FMain.ReallySaveAllSettings.5085 FMain.AllInit_Pre.416 FMain.MainInit.1178 zzzFake.Start.58 StartClass.main.41 ? 
```

I installed it on openSUSE Tumbleweed as a native package with gambas dependencies.

**Comment by kokoko3k** [comment]
Hi there, it is working fine here, with:
Gambas3  3.17.3
xt7-player-mpv 0.34.3172
It with those versions you still have problems, i suggest you to start with a clean profile.
Remove or rename:  ~/.config/gambas3/xt7-Player-mpv/

**Comment by Freemason-12** [comment]
I have:
Gambas3 3.18.0
xt7-player-mpv 0.24.392
Should I upgrade xt7-player-mpv or downgrade Gambas3 or both?

**Comment by Freemason-12** [comment]
I installed the latest version of the player, it launched but now I have no audio

**Comment by kokoko3k** [comment]
Is it turned up?
Mouse wheel on the video should take care of it, or click the speaker icon in the lower right part of the window and modve the slider.
If it is not it, please, post the output of the log window when you have no audio
main menu (top left) -> ? -> show logs
Both tabs, please (output and modules)

**Comment by Freemason-12** [comment]
Oh, yeah, sorry, did not see the volume being low.
Also, how can I turn on vaapi there? It's not being used in this player although i managed to make it work on mpv

**Comment by kokoko3k** [comment]
Select a video decode method in general options -> video
