### ISSUE TITLE
Problems with subtitles?

### ISSUE THREAD

**Issue by x4tur4ng4** [kokoko3k/xt7-player-mpv#35]
Are there any known issues with loading subtitles? I am unable to play subtitles in the player. I tried .srt and .ass subtitles, they all fail in xt7, in vlc and smplayer they work perfectly. The logs did not generate an error regarding subtitles. The subtitles appear in the player options menu, but when I try to use them, nothing happens. The logs don't show anything regarding subtitles, I don't know where to start to try to resolve this. Linux Debian 12 amd64, intel i7 lga 1155 12 gb ram. Thank you for your attention.

**Comment by kokoko3k** [comment]
You are right!
I don't know if something changed in mpv lately, but it seems this option needs to be set to off:
[ ] Display forced subtitles only by default
It is in general options, language.

![Screenshot_20231124_144250](https://github.com/kokoko3k/xt7-player-mpv/assets/1230726/6386b67c-5516-4543-9245-b0b9c0c2d998)


Please let me know if this fixes it for you.

**Comment by x4tur4ng4** [comment]
I managed to solve it! In the general options, Language tab, I unchecked the Display forced subtitles only by default box. I also installed the Bitstram Vera Sans font, this font is not installed by default on Linux distributions. I think it would be interesting to inform this in the dependencies necessary to compile on Linux, since xt7 uses this font as default. Note: When I couldn't reproduce the subtitles, I tried using standard Linux fonts, and it still didn't work, so installing the Bitstram Vera Sans font is more for aesthetic reasons and personal taste. What should have really resolved it, in my case, was unchecking the box (Display forced subtitles only by default). Problem solved! Thanks for your attention, and sorry for my English by Google. Hugs from Brazil.

**Comment by x4tur4ng4** [comment]
Sorry, I had already found the solution to my case before seeing your message, so I responded with a giant text. But yes, this option solved the problem! I love the xt7 interface, in general I love all-in-1 programs. If the xt7 had support for IPTV, along the same lines as yuki-iptv, this player would be my Swiss army knife :)
