### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by 3052** [kokoko3k/xt7-player-mpv#37]

**Comment by kokoko3k** [comment]
Care to explain what the problem is?

**Comment by 3052** [comment]
I have no idea where to find the program to download, or instruction on how to install the program

**Comment by kokoko3k** [comment]
If your distro does not package it, have you tried to follow the instructions on the main readme or on the main repo page ?(requirements, compilation)

**Comment by 3052** [comment]
I am on Windows

**Comment by kokoko3k** [comment]
Sorry, I don't use that since decades, so I really don't know how or even if it would run.
Maybe with some efforts you could find a gambas version for it.
