### ISSUE TITLE
Bug in first running

### ISSUE THREAD

**Issue by aalsabi** [kokoko3k/xt7-player-mpv#5]
[6] Type mismatch: wanted Float, got String instead.
SubAndOsd.ParseSubGui.73
# 

xt7-player-mpv-master: 0.9.2371

System.fullversion: 3.8.90

System.Architecture: x86_64

mpv: 
mpv git-d04d238 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Fri Sep  4 16:31:50 UTC 2015
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: N-74831-ga51d424

**Comment by kokoko3k** [comment]
Is it the same bug as for https://github.com/kokoko3k/xt7-player-mpv/issues/4 ?
By "first running" do you mean is the first time you try to start xt7 on that machine?
Is your xt7-player built from git?

**Comment by aalsabi** [comment]
Yes , Sorry for That

**Comment by kokoko3k** [comment]
Ok, i'd need answers to the other questions too.
Anyway i'm unable to reproduce your issue.
I suspect something wrong is written in a field of the subtitles window (if you're using the latest git, probably at least the border color field); so one thing that may be useful to find out why you have the problem is to see your config files.

In particular the file:
~/.config/gambas3/xt7-Player-mpv/default.profile/SubAndOsd
or, if you don't use the default profile, this:
~/.config/gambas3/xt7-Player-mpv/*/SubAndOsd

Can you post them?
...you can even try to delete them after quitting xt7 and start over to see if it correct the issue.

**Comment by aalsabi** [comment]
:) it is yes for them all :)

**Comment by kokoko3k** [comment]
Deleting the file fixed that too?
If not, i still need it.

**Comment by aalsabi** [comment]
Sorry for delay ,
Deleting files didn't fix the issue  Here are the files you asked for
http://www.filedropper.com/substar

**Comment by kokoko3k** [comment]
Seems that some text boxes numerical values are translated to Arabic when saved to file.
Could you please try to:

```
#rm -R ~/.config/gambas3/xt7-Player-mpv/
#LC_ALL=C xt7-player-mpv
```

(or xt7-player-mpv-git; depending on the executable name)

If this way it starts, i've something to work on.

Did you use xt7-player in the past and it worked?
If yes, when you started to have the issue?

-EDIT
Meantime i commited another change  ( https://github.com/kokoko3k/xt7-player-mpv/commit/efec7c9f56b7cc7d843fd25369a8d019faaeb0e2 ) to git which hopefully will solve your issue.

Remember to delete ~/.config/gambas3/xt7-Player-mpv/ before trying.

**Comment by aalsabi** [comment]
with this command
LC_ALL=C xt7-player-mpv
the crash appears immediately with the same message

On Wed, Sep 9, 2015 at 9:30 AM, Antonio Orefice notifications@github.com
wrote:

> Seems that some text boxes numerical values are translated to Arabic when
> saved to file.
> Could you please try to:
> 
> #rm -R ~/.config/gambas3/xt7-Player-mpv/
> #LC_ALL=C xt7-player-mpv
> 
> (or xt7-player-mpv-git; depending on the executable name)
> 
> If this way it starts, i've something to work on.
> 
> Did you use xt7-player in the past and it worked?
> If yes, when you started to have the issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kokoko3k/xt7-player-mpv/issues/5#issuecomment-138802742
> .

## 

*Abdullah S Al-sabi *
*CEO *

(+966) 599 433055
(+966) 538 545717
alsabi.abdullah@gmail.com

**Comment by kokoko3k** [comment]
Did you tried to use the latest git too?

**Comment by aalsabi** [comment]
Yes , Just now And it's O.K.

Thanks

On Thu, Sep 10, 2015 at 10:07 AM, Antonio Orefice notifications@github.com
wrote:

> Did you tried to use the latest git yoo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kokoko3k/xt7-player-mpv/issues/5#issuecomment-139134974
> .

## 

*Abdullah S Al-sabi *
*CEO *

(+966) 599 433055
(+966) 538 545717
alsabi.abdullah@gmail.com
